name: Release

env:
  PACKAGE_NAME: docker-stats-exporter

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43 # v7
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: release
          workflow: ci.yml
          workflow_conclusion: success

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: .github/release/package.json

      - name: Install semantic-release
        run: npm ci --prefix .github/release

      - name: Generate version
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --prefix .github/release semantic-release
